'use client';

import React, { useState } from 'react';
import { UserButton, useUser } from '@clerk/nextjs';
import Questionnaire from './components/Questionnaire';
import RadarChartComponent from './components/RadarChart';
import Recommendation from './components/Recommendation';
import { AssessmentResult, DomainScore } from './types';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';

const AssessmentPage = () => {
  const { user, isLoaded, isSignedIn } = useUser();
  const [assessmentComplete, setAssessmentComplete] = useState(false);
  const [result, setResult] = useState<AssessmentResult | null>(null);

  if (!isLoaded) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500 mb-4"></div>
          <p className="text-lg text-gray-600">Loading...</p>
        </div>
      </div>
    );
  }

  if (!isSignedIn) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8">
        <Card className="text-center">
          <CardHeader>
            <CardTitle>Access Denied</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="mb-4">You need to sign in to access the assessment tool.</p>
            <Button onClick={() => window.location.href = '/sign-in'}>Sign In</Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const handleAssessmentSubmit = (answers: Record<string, number>) => {
    // Calculate scores for each domain based on the answers
    const mea01Questions = [
      'MEA01-Q1', 'MEA01-Q2', 'MEA01-Q3', 'MEA01-Q4', 'MEA01-Q5'
    ];
    const mea02Questions = [
      'MEA02-Q1', 'MEA02-Q2', 'MEA02-Q3', 'MEA02-Q4',
      'MEA02-Q5', 'MEA02-Q6', 'MEA02-Q7', 'MEA02-Q8'
    ];
    const mea03Questions = [
      'MEA03-Q1', 'MEA03-Q2', 'MEA03-Q3', 'MEA03-Q4'
    ];

    // Calculate domain scores
    const mea01Score = mea01Questions.reduce((sum, q) => sum + (answers[q] || 0), 0) / mea01Questions.length;
    const mea02Score = mea02Questions.reduce((sum, q) => sum + (answers[q] || 0), 0) / mea02Questions.length;
    const mea03Score = mea03Questions.reduce((sum, q) => sum + (answers[q] || 0), 0) / mea03Questions.length;

    // Calculate overall score
    const overallScore = (mea01Score + mea02Score + mea03Score) / 3;

    // Prepare domain scores for the chart
    const domainScores: DomainScore[] = [
      {
        domain: 'MEA01',
        score: parseFloat(mea01Score.toFixed(2)),
        maxScore: 5,
        percentage: Math.min(100, (mea01Score / 5) * 100)
      },
      {
        domain: 'MEA02',
        score: parseFloat(mea02Score.toFixed(2)),
        maxScore: 5,
        percentage: Math.min(100, (mea02Score / 5) * 100)
      },
      {
        domain: 'MEA03',
        score: parseFloat(mea03Score.toFixed(2)),
        maxScore: 5,
        percentage: Math.min(100, (mea03Score / 5) * 100)
      }
    ];

    // Prepare assessment result
    const assessmentResult: AssessmentResult = {
      overallScore: parseFloat(overallScore.toFixed(2)),
      mea01Score: parseFloat(mea01Score.toFixed(2)),
      mea02Score: parseFloat(mea02Score.toFixed(2)),
      mea03Score: parseFloat(mea03Score.toFixed(2)),
      domainScores,
      recommendations: [], // Recommendations will be generated by the Recommendation component
      maxPossibleScore: 5
    };

    setResult(assessmentResult);
    setAssessmentComplete(true);
  };

  const resetAssessment = () => {
    setAssessmentComplete(false);
    setResult(null);
  };

  if (assessmentComplete && result) {
    // Data for radar chart
    const chartData = [
      { subject: 'MEA01', score: result.mea01Score, fullMark: 5 },
      { subject: 'MEA02', score: result.mea02Score, fullMark: 5 },
      { subject: 'MEA03', score: result.mea03Score, fullMark: 5 },
    ];

    return (
      <div className="max-w-6xl mx-auto px-4 py-8">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-3xl font-bold text-gray-800">Assessment Results</h1>
          <UserButton afterSignOutUrl="/" />
        </div>

        <div className="mb-8 text-center">
          <p className="text-gray-600">
            Your organization's COBIT maturity level assessment results
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
          {/* Scores Summary */}
          <div className="bg-white p-6 rounded-lg shadow-md">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Maturity Scores</h2>
            <div className="space-y-4">
              <div className="flex justify-between items-center p-3 bg-blue-50 rounded">
                <span className="font-medium">Overall Maturity Level:</span>
                <span className="text-xl font-bold text-blue-600">
                  {result.overallScore.toFixed(2)} / 5.00
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="p-3 bg-green-50 rounded text-center">
                  <div className="text-sm text-gray-600">MEA01</div>
                  <div className="text-lg font-bold text-green-600">
                    {result.mea01Score.toFixed(2)}
                  </div>
                </div>
                <div className="p-3 bg-green-50 rounded text-center">
                  <div className="text-sm text-gray-600">MEA02</div>
                  <div className="text-lg font-bold text-green-600">
                    {result.mea02Score.toFixed(2)}
                  </div>
                </div>
                <div className="p-3 bg-green-50 rounded text-center">
                  <div className="text-sm text-gray-600">MEA03</div>
                  <div className="text-lg font-bold text-green-600">
                    {result.mea03Score.toFixed(2)}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Radar Chart */}
          <div className="bg-white p-6 rounded-lg shadow-md">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Maturity Visualization</h2>
            <RadarChartComponent data={chartData} />
          </div>
        </div>

        {/* Recommendations */}
        <div className="bg-white p-6 rounded-lg shadow-md mb-8">
          <Recommendation result={result} />
        </div>

        <div className="flex justify-center">
          <button
            onClick={resetAssessment}
            className="px-6 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 font-medium"
          >
            Start New Assessment
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-800">COBIT Assessment Tool</h1>
        <UserButton afterSignOutUrl="/" />
      </div>

      <div className="mb-8">
        <div className="prose max-w-none">
          <p className="text-gray-700 mb-4">
            The COBIT Assessment Tool helps evaluate your organization's IT governance maturity level based on the MEA (Monitor, Evaluate, and Assess) domain of COBIT 5.
          </p>
          <p className="text-gray-700 mb-4">
            This assessment focuses on three key areas:
          </p>
          <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
            <li><strong>MEA01 - Performance and Conformance:</strong> Evaluates how your organization monitors performance and conformance with established targets.</li>
            <li><strong>MEA02 - System of Internal Control:</strong> Assesses your internal control systems and their effectiveness.</li>
            <li><strong>MEA03 - Compliance with External Requirements:</strong> Reviews how well your organization complies with external regulations and requirements.</li>
          </ul>
          <p className="text-gray-700">
            Each practice is scored from 0 (Incomplete) to 5 (Optimizing) based on the degree of achievement.
          </p>
        </div>
      </div>

      <div className="bg-white p-6 rounded-lg shadow-md">
        <Questionnaire onSubmit={handleAssessmentSubmit} />
      </div>
    </div>
  );
};

export default AssessmentPage;